version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      ".env"
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    depends_on:
      - postgres
