[project]
name = "Grandmothers_garden"
version = "1.0.0"
dependencies = [
    "streamlit<=3.18.0",
    "pandas>=2.2.0",
    "altair>=5.4.1",
    "pydantic>=2.8.2",
    "pydantic-settings>=2.4.0",
    "sqlalchemy>=2.0.32",
    "psycopg>=3.2.0"
]
